apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: oauth-server
build:
  artifacts:
    - image: trojan2877/oauth-server
      context: .
      jib:
        project: com.trojan:oauth-server
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml